catalog:
  db:
    endpoint: "bedrock-mysql.c0bmkyg44ue5.us-east-1.rds.amazonaws.com"
    name: "catalog"
    username: "admin"
    passwordSecret: "mysql-creds"

orders:
  db:
    endpoint: "bedrock-postgres.c0bmkyg44ue5.us-east-1.rds.amazonaws.com"
    name: "orders"
    username: "bedrockadmin"
    passwordSecret: "postgres-creds"

carts:
  dynamodb:
    tableName: "bedrock-carts"
    region: "us-east-1"
    createDynamoDBTable: false

activemq:
  enabled: true

redis:
  enabled: true

ui:
  ingress:
    enabled: true
    className: "alb"
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
